# -*- coding: utf-8 -*-
"""BDS Testing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TnmEY4TTblYOh5zAH5QyIukM-Sfl8oeZ
"""

import numpy as np
import pandas as pd
from scipy.spatial import distance_matrix
from scipy.stats import norm

from google.colab import drive
drive.mount('/content/drive/')

df = pd.read_csv('/content/drive/MyDrive/Chaos and Fractals/BDSL_test_data.csv')

distance = df['S&P 500 return']
dist_array_1d = np.array(distance)
dist_array_2d = dist_array_1d.reshape(-1,1)
print(dist_array_2d)

dist_matrix = distance_matrix(dist_array_2d, dist_array_2d)
dist_matrix = np.abs(dist_matrix)
print(dist_matrix)

percentile = 70
epsilon = np.percentile(dist_matrix, percentile)
print(epsilon)

sample_size = dist_array_1d.size
print(sample_size)

pairs_matrix = np.zeros((sample_size, sample_size))
smaller_values = dist_matrix <= epsilon
pairs_matrix[smaller_values] = 1
print(pairs_matrix)

c1 = np.sum(pairs_matrix) / (sample_size ** 2)
print(c1)

triples_matrix = np.dot(pairs_matrix, pairs_matrix)
k = np.sum(triples_matrix) / (sample_size ** 3)
print(k)

m2_matrix = np.zeros((sample_size, sample_size))
i = 1
while i < sample_size:
  j = 1
  while j < sample_size:
    m2_matrix[i][j] = pairs_matrix[i][j] * pairs_matrix[i - 1][j - 1]
    j += 1
  i += 1
print(m2_matrix)

c2 = (np.sum(m2_matrix) - (sample_size - 1)) / ((sample_size - 1) ** 2 - (sample_size - 1))
print(c2)

c12 = (np.sum(pairs_matrix[1:, 1:]) - (sample_size - 1)) / ((sample_size - 1) ** 2 - (sample_size - 1))
print(c12)

difference = c2 - (c12 ** 2)
print(difference)

variance = 4 * (k ** 2 + 2 * k ** (2-1) * c1 ** (2 * 1) + (2-1)** 2 * c1 ** (2 * 2) - k * 2 ** 2*c1** (2 * 2 - 2))
print(variance)

stdev = np.sqrt(variance / (sample_size - 2 + 1))
print(stdev)

z_stat = difference / stdev
print(z_stat)

p_value = 1 - norm.cdf(abs(z_stat))
print(p_value)

import statsmodels.api as sm

test_stat, p_value = sm.tsa.stattools.bds(distance, max_dim = 4, epsilon = 0.7)
print(test_stat)
print(p_value)