# -*- coding: utf-8 -*-
"""MSCI World Fractal Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ai7NP_MMF-BlTFJ8mSRZakSlBz6UeN-R
"""

!pip install nolds

import nolds
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/Chaos and Fractals/DevelopedMarkets.csv')

df['Return'] = df['Values'].pct_change()
data_raw = df['Return']
data_raw_price = df['Values']
nan_mask = pd.isna(data_raw)
nan_mask_price = pd.isna(data_raw_price)
data_price = data_raw_price[~nan_mask_price]
data = data_raw[~nan_mask]
print(data)

def rs(data, n, unbiased=True):
  data = np.asarray(data)
  total_N = len(data)
  m = total_N // n # number of sequences
  # cut values at the end of data to make the array divisible by n
  data = data[:total_N - (total_N % n)]
  # split remaining data into subsequences of length n
  seqs = np.reshape(data, (m, n))
  # calculate means of subsequences
  means = np.mean(seqs, axis=1)
  # normalize subsequences by substracting mean
  y = seqs - means.reshape((m, 1))
  # build cumulative sum of subsequences
  y = np.cumsum(y, axis=1)
  # find ranges
  r = np.max(y, axis=1) - np.min(y, axis=1)
  # find standard deviation
  # we should use the unbiased estimator, since we do not know the true mean
  s = np.std(seqs, axis=1, ddof=1 if unbiased else 0)
  # some ranges may be zero and have to be excluded from the analysis
  idx = np.where(r != 0)
  r = r[idx]
  s = s[idx]
  # it may happen that all ranges are zero (if all values in data are equal)
  if len(r) == 0:
    return np.nan
  else:
    # return mean of r/s along subsequence index
    return np.mean(r / s)

cycle_iterator = 10
log_obs = []
v_rs = []

while cycle_iterator <= 400:
  temp_obs = np.log(cycle_iterator)
  log_obs.append(temp_obs)

  temp_rs = rs(data, cycle_iterator)
  v_rs.append(temp_rs / np.sqrt(cycle_iterator))

  cycle_iterator += 1

plt.plot(log_obs, v_rs, "r-")
plt.xlabel("Log(Number of Observations)")
plt.ylabel("V-Stat")
plt.title("Cycle Chart")
plt.show()

start = 85
sub_arr = np.array(v_rs[start:145])
tolerance = 1e-6
time_index = np.where(np.abs(sub_arr - 1.6054669721603883) < tolerance)[0]
cycle_length = start + time_index
print(cycle_length[0])

hurst_exponent = nolds.hurst_rs(data, debug_plot = True)
print(f"Hurst Exponent: {hurst_exponent}")

!pip install git+https://github.com/manu-mannattil/nolitsa.git

import scipy
import numba
from nolitsa import dimension as ed

dim = np.arange(1, 15, 1)
f1, f2, f3 = ed.fnn(data_price, tau=1, dim=dim, window=0, metric='euclidean')
plt.title(r'FNN with Euclidean Metric')
plt.xlabel(r'Embedding dimension $d$')
plt.ylabel(r'FNN (%)')
plt.plot(dim, 100 * f1, 'bo--', label=r'Test I')
#plt.plot(dim, 100 * f2, 'g^--', label=r'Test II')
#plt.plot(dim, 100 * f3, 'rs-', label=r'Test I + II')
#plt.legend()
plt.show()

print(f1)

t1, t2, t12 = ed.fnn(data)
embedding_dimension_float = t12 * 100
embedding_dimension = np.ceil(embedding_dimension_float)
embedding_dimension_int = int(embedding_dimension[0])
print(embedding_dimension_int)

corr_dim = nolds.corr_dim(data_price, 4)
print(f"Correlation Dimension: {corr_dim}")

import statsmodels.api as sm

test_stat, p_value = sm.tsa.stattools.bds(data, max_dim = 4, epsilon = 0.7)
print(test_stat)
print(p_value)