# -*- coding: utf-8 -*-
"""SPX Pareto Distribution Fitting Method

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tg2yPYX-aPkfcOqNtDX_grGmOD2eQGCu
"""

import numpy as np
import scipy.stats as stats
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('SPX.csv')

df['Returns'] = df['Value'].pct_change()

abs_value_returns = pd.DataFrame(df['Returns'].abs())

print(abs_value_returns['Returns'])

threshold = abs_value_returns.quantile(0.90)

tail_returns = abs_value_returns[abs_value_returns['Returns'] >= float(threshold)]
print(type(len(tail_returns)))

num_bins = np.ceil(np.sqrt(len(tail_returns)))
plt.hist(tail_returns, bins = int(num_bins), color = 'blue', edgecolor = 'black')
plt.show()

!pip3 install openturns
import openturns as ot

data_points = tail_returns['Returns']
ot_data = ot.Sample([[i] for i in data_points])
pareto_distribution = ot.ParetoFactory().build(ot_data)
print(pareto_distribution)

#from openturns.viewer import View
#graph_ot = ot_data.stack(ot.Sample(len(ot_data), 1))
#scatter = ot.Cloud(graph_ot)
#pdf_graph = pareto_distribution.drawPDF()
#pdf_graph.add(scatter)
#pdf_graph.setTitle(str(pareto_distribution))
#View(pdf_graph, add_legend=False)

ks_test = ot.FittingTest.Kolmogorov(ot_data, pareto_distribution)
print(ks_test.getPValue())