# -*- coding: utf-8 -*-
"""SPX Pareto P-Values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzEz6XmdXjxG_G_JxHgkCJe1VjVbGMKa
"""

!pip3 install openturns

import numpy as np
import scipy.stats as stats
import pandas as pd
import matplotlib.pyplot as plt
import openturns as ot
from sklearn.model_selection import train_test_split

df = pd.read_csv('/content/SPX.csv')
df['Returns'] = df['Value'].pct_change()
abs_value_returns = pd.DataFrame(df['Returns'].abs()).iloc[1:]
print(abs_value_returns)

iterator = 0.90
p_value_moments_list = []
threshold_list = []
while iterator < .982:
  threshold = abs_value_returns.quantile(iterator)
  tail_returns = abs_value_returns[abs_value_returns['Returns'] >= float(threshold)]
  data_points = tail_returns['Returns']
  ot_data_train = ot.Sample([[i] for i in data_points])
  pareto_distribution = ot.ParetoFactory().buildMethodOfMoments(ot_data_train)
  ks_test = ot.FittingTest.Kolmogorov(ot_data_train, pareto_distribution)
  p_value = ks_test.getPValue()
  threshold_list.append(iterator * 100)
  p_value_moments_list.append(p_value)
  iterator = iterator + 0.0001

iterator = 0.90
p_value_least_squares_list = []
threshold_list = []
while iterator < .982:
  threshold = abs_value_returns.quantile(iterator)
  tail_returns = abs_value_returns[abs_value_returns['Returns'] >= float(threshold)]
  data_points = tail_returns['Returns']
  ot_data_train = ot.Sample([[i] for i in data_points])
  pareto_distribution = ot.ParetoFactory().buildMethodOfLeastSquares(ot_data_train)
  ks_test = ot.FittingTest.Kolmogorov(ot_data_train, pareto_distribution)
  p_value = ks_test.getPValue()
  threshold_list.append(iterator * 100)
  p_value_least_squares_list.append(p_value)
  iterator = iterator + 0.0001

iterator = 0.90
p_value_maximum_likelihood_list = []
threshold_list = []
while iterator < .982:
  threshold = abs_value_returns.quantile(iterator)
  tail_returns = abs_value_returns[abs_value_returns['Returns'] >= float(threshold)]
  data_points = tail_returns['Returns']
  ot_data_train = ot.Sample([[i] for i in data_points])
  pareto_distribution = ot.ParetoFactory().buildMethodOfLikelihoodMaximization(ot_data_train)
  ks_test = ot.FittingTest.Kolmogorov(ot_data_train, pareto_distribution)
  p_value = ks_test.getPValue()
  threshold_list.append(iterator * 100)
  p_value_maximum_likelihood_list.append(p_value)
  iterator = iterator + 0.0001

plt.scatter(threshold_list, p_value_moments_list, label = "Moments-Based Build", color = 'blue')
plt.scatter(threshold_list, p_value_least_squares_list, label = "Least Squares Build", color = 'red')
plt.scatter(threshold_list, p_value_maximum_likelihood_list, label = "Maximum Likelihood Build", color = 'green')
plt.xlabel("Percentage of Data Excluded")
plt.ylabel("P-Value")
plt.title("P-Values Based on Size")
plt.legend()
plt.show()

return_train, return_test = train_test_split(abs_value_returns, train_size = 0.8)

iterator = 0.90
p_value_least_squares_train_list = []
threshold_least_squares_train_list = []
pareto_distribution_least_squares_train_list = []
while iterator < .98:
  threshold = return_train.quantile(iterator)
  tail_returns = return_train[return_train['Returns'] >= float(threshold)]
  data_points = tail_returns['Returns']
  ot_data_train = ot.Sample([[i] for i in data_points])
  pareto_distribution = ot.ParetoFactory().build(ot_data_train)
  pareto_distribution_least_squares_train_list.append(pareto_distribution)
  ks_test = ot.FittingTest.Kolmogorov(ot_data_train, pareto_distribution)
  p_value = ks_test.getPValue()
  threshold_least_squares_train_list.append(iterator * 100)
  p_value_least_squares_train_list.append(p_value)
  iterator = iterator + 0.0001

iterator = 0.90
p_value_moments_train_list = []
threshold_moments_train_list = []
pareto_distribution_moments_train_list = []
while iterator < .98:
  threshold = return_train.quantile(iterator)
  tail_returns = return_train[return_train['Returns'] >= float(threshold)]
  data_points = tail_returns['Returns']
  ot_data_train = ot.Sample([[i] for i in data_points])
  pareto_distribution = ot.ParetoFactory().buildMethodOfMoments(ot_data_train)
  pareto_distribution_moments_train_list.append(pareto_distribution)
  ks_test = ot.FittingTest.Kolmogorov(ot_data_train, pareto_distribution)
  p_value = ks_test.getPValue()
  threshold_moments_train_list.append(iterator * 100)
  p_value_moments_train_list.append(p_value)
  iterator = iterator + 0.0001

iterator = 0.90
p_value_maximum_likelihood_train_list = []
threshold_maximum_likelihood_train_list = []
pareto_distribution_maximum_likelihood_train_list = []
while iterator < .98:
  threshold = return_train.quantile(iterator)
  tail_returns = return_train[return_train['Returns'] >= float(threshold)]
  data_points = tail_returns['Returns']
  ot_data_train = ot.Sample([[i] for i in data_points])
  pareto_distribution = ot.ParetoFactory().buildMethodOfLikelihoodMaximization(ot_data_train)
  pareto_distribution_maximum_likelihood_train_list.append(pareto_distribution)
  ks_test = ot.FittingTest.Kolmogorov(ot_data_train, pareto_distribution)
  p_value = ks_test.getPValue()
  threshold_maximum_likelihood_train_list.append(iterator * 100)
  p_value_maximum_likelihood_train_list.append(p_value)
  iterator = iterator + 0.0001

iterator = 0.90
p_value_least_squares_test_list = []
threshold_least_squares_test_list = []
k = 0
while iterator < .98:
  threshold = return_test.quantile(iterator)
  tail_returns = return_test[return_test['Returns'] >= float(threshold)]
  data_points = tail_returns['Returns']
  ot_data_test = ot.Sample([[i] for i in data_points])
  ks_test = ot.FittingTest.Kolmogorov(ot_data_test, pareto_distribution_least_squares_train_list[k])
  p_value = ks_test.getPValue()
  threshold_least_squares_test_list.append(iterator * 100)
  p_value_least_squares_test_list.append(p_value)
  iterator = iterator + 0.0001
  k = k + 1

iterator = 0.90
p_value_moments_test_list = []
threshold_moments_test_list = []
k = 0
while iterator < .98:
  threshold = return_test.quantile(iterator)
  tail_returns = return_test[return_test['Returns'] >= float(threshold)]
  data_points = tail_returns['Returns']
  ot_data_test = ot.Sample([[i] for i in data_points])
  ks_test = ot.FittingTest.Kolmogorov(ot_data_test, pareto_distribution_moments_train_list[k])
  p_value = ks_test.getPValue()
  threshold_moments_test_list.append(iterator * 100)
  p_value_moments_test_list.append(p_value)
  iterator = iterator + 0.0001
  k = k + 1

iterator = 0.90
p_value_maximum_likelihood_test_list = []
threshold_maximum_likelihood_test_list = []
k = 0
while iterator < .98:
  threshold = return_test.quantile(iterator)
  tail_returns = return_test[return_test['Returns'] >= float(threshold)]
  data_points = tail_returns['Returns']
  ot_data_test = ot.Sample([[i] for i in data_points])
  ks_test = ot.FittingTest.Kolmogorov(ot_data_test, pareto_distribution_maximum_likelihood_train_list[k])
  p_value = ks_test.getPValue()
  threshold_maximum_likelihood_test_list.append(iterator * 100)
  p_value_maximum_likelihood_test_list.append(p_value)
  iterator = iterator + 0.0001
  k = k + 1

#plt.figure(figsize=(20,12))
plt.scatter(threshold_least_squares_train_list, p_value_least_squares_train_list, label = 'Training Data', color = 'red')
plt.scatter(threshold_least_squares_test_list, p_value_least_squares_test_list, label = 'Test Data', color = 'purple')
plt.xlabel("Percentage of Data Excluded")
plt.ylabel("P-Value")
plt.title("P-Values Based on Size (Method of Least Squares)")
plt.legend()
plt.show()

#plt.figure(figsize=(20,12))
plt.scatter(threshold_moments_train_list, p_value_moments_train_list, label = 'Training Data', color = 'red')
plt.scatter(threshold_moments_test_list, p_value_moments_test_list, label = 'Test Data', color = 'purple')
plt.xlabel("Percentage of Data Excluded")
plt.ylabel("P-Value")
plt.title("P-Values Based on Size (Method of Moments)")
plt.legend()
plt.show()

#plt.figure(figsize=(20,12))
plt.scatter(threshold_maximum_likelihood_train_list, p_value_maximum_likelihood_train_list, label = 'Training Data', color = 'red')
plt.scatter(threshold_maximum_likelihood_test_list, p_value_maximum_likelihood_test_list, label = 'Test Data', color = 'purple')
plt.xlabel("Percentage of Data Excluded")
plt.ylabel("P-Value")
plt.title("P-Values Based on Size (Method of Maximum Likelihood)")
plt.legend()
plt.show()

fragments = 4
iteration_step = len(abs_value_returns) // fragments
start_index = 0
end_index = 0
i = 1
fragment_list = []
while i <= fragments:
  if i != 1:
    start_index = end_index + 1
  end_index = start_index + iteration_step
  new_df = abs_value_returns[start_index: end_index]
  fragment_list.append(new_df)
  i += 1

fragment_p_value_list = []
j = 0
while j < fragments:
  iterator = 0.90
  p_value_list = []
  threshold_list = []
  fragment_data = fragment_list[j]
  while iterator < .99:
    threshold = fragment_data.quantile(iterator)
    tail_returns = fragment_data[fragment_data['Returns'] >= float(threshold)]
    data_points = tail_returns['Returns']
    ot_data_train = ot.Sample([[i] for i in data_points])
    pareto_distribution = ot.ParetoFactory().build(ot_data_train)
    ks_test = ot.FittingTest.Kolmogorov(ot_data_train, pareto_distribution)
    p_value = ks_test.getPValue()
    threshold_list.append(iterator * 100)
    p_value_list.append(p_value)
    iterator = iterator + 0.0001
  fragment_p_value_list.append(p_value_list)
  j +=1

fragment_p_value_list = []
j = 0
while j < fragments:
  iterator = 0.90
  p_value_list = []
  threshold_list = []
  fragment_data = fragment_list[j]
  while iterator < .99:
    threshold = fragment_data.quantile(iterator)
    tail_returns = fragment_data[fragment_data['Returns'] >= float(threshold)]
    data_points = tail_returns['Returns']
    ot_data_train = ot.Sample([[i] for i in data_points])
    pareto_distribution = ot.ParetoFactory().build(ot_data_train)
    ks_test = ot.FittingTest.Kolmogorov(ot_data_train, pareto_distribution)
    p_value = ks_test.getPValue()
    threshold_list.append(iterator * 100)
    p_value_list.append(p_value)
    iterator = iterator + 0.0001
  fragment_p_value_list.append(p_value_list)
  j +=1

k = 0
while k < fragments:
  plt.scatter(threshold_list, fragment_p_value_list[k], label = f"{k + 1}")
  k += 1
plt.xlabel("Percentage of Data Excluded")
plt.ylabel("P-Value")
plt.title("P-Values Based on Size")
plt.legend()
plt.show()